//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//


package cz.stormware.schema.invoice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.invoice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvoiceResponse_QNAME = new QName("http://www.stormware.cz/schema/invoice.xsd", "invoiceResponse");
    private final static QName _Invoice_QNAME = new QName("http://www.stormware.cz/schema/invoice.xsd", "invoice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.invoice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceItemType }
     * 
     */
    public InvoiceItemType createInvoiceItemType() {
        return new InvoiceItemType();
    }

    /**
     * Create an instance of {@link InvoiceHeaderType }
     * 
     */
    public InvoiceHeaderType createInvoiceHeaderType() {
        return new InvoiceHeaderType();
    }

    /**
     * Create an instance of {@link InvoiceSummaryType }
     * 
     */
    public InvoiceSummaryType createInvoiceSummaryType() {
        return new InvoiceSummaryType();
    }

    /**
     * Create an instance of {@link InvoiceHeaderType.PaymentAccount }
     * 
     */
    public InvoiceHeaderType.PaymentAccount createInvoiceHeaderTypePaymentAccount() {
        return new InvoiceHeaderType.PaymentAccount();
    }

    /**
     * Create an instance of {@link InvoiceDetailType }
     * 
     */
    public InvoiceDetailType createInvoiceDetailType() {
        return new InvoiceDetailType();
    }

    /**
     * Create an instance of {@link InvoiceType }
     * 
     */
    public InvoiceType createInvoiceType() {
        return new InvoiceType();
    }

    /**
     * Create an instance of {@link InvoiceResponseType }
     * 
     */
    public InvoiceResponseType createInvoiceResponseType() {
        return new InvoiceResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/invoice.xsd", name = "invoiceResponse")
    public JAXBElement<InvoiceResponseType> createInvoiceResponse(InvoiceResponseType value) {
        return new JAXBElement<InvoiceResponseType>(_InvoiceResponse_QNAME, InvoiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/invoice.xsd", name = "invoice")
    public JAXBElement<InvoiceType> createInvoice(InvoiceType value) {
        return new JAXBElement<InvoiceType>(_Invoice_QNAME, InvoiceType.class, null, value);
    }

}
