//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//


package cz.stormware.schema.invoice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sphereTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sphereTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="business"/>
 *     &lt;enumeration value="loan"/>
 *     &lt;enumeration value="specificRegulations"/>
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="cheques"/>
 *     &lt;enumeration value="exchangeRateDifference"/>
 *     &lt;enumeration value="penalty"/>
 *     &lt;enumeration value="labourLaw"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sphereTypeType")
@XmlEnum
public enum SphereTypeType {


    /**
     * Obchodní.
     * 
     */
    @XmlEnumValue("business")
    BUSINESS("business"),

    /**
     * P\u016fj\u010dka.
     * 
     */
    @XmlEnumValue("loan")
    LOAN("loan"),

    /**
     * Zvl. p\u0159edpis.
     * 
     */
    @XmlEnumValue("specificRegulations")
    SPECIFIC_REGULATIONS("specificRegulations"),

    /**
     * Ostatní.
     * 
     */
    @XmlEnumValue("other")
    OTHER("other"),

    /**
     * Šeky.
     * 
     */
    @XmlEnumValue("cheques")
    CHEQUES("cheques"),

    /**
     * Kursové rozdíly.
     * 
     */
    @XmlEnumValue("exchangeRateDifference")
    EXCHANGE_RATE_DIFFERENCE("exchangeRateDifference"),

    /**
     * Penále.
     * 
     */
    @XmlEnumValue("penalty")
    PENALTY("penalty"),

    /**
     * Pracovn\u011bprávní.
     * 
     */
    @XmlEnumValue("labourLaw")
    LABOUR_LAW("labourLaw");
    private final String value;

    SphereTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SphereTypeType fromValue(String v) {
        for (SphereTypeType c: SphereTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
