//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.intdoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intDocType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="intDocType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="intDocHeader" type="{http://www.stormware.cz/schema/intDoc.xsd}intDocHeaderType"/>
 *         &lt;element name="intDocDetail" type="{http://www.stormware.cz/schema/intDoc.xsd}intDocDetailType" minOccurs="0"/>
 *         &lt;element name="intDocSummary" type="{http://www.stormware.cz/schema/intDoc.xsd}intDocSummaryType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.stormware.cz/schema/intDoc.xsd}intVersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "intDocType", propOrder = {
    "intDocHeader",
    "intDocDetail",
    "intDocSummary"
})
public class IntDocType {

    @XmlElement(required = true)
    protected IntDocHeaderType intDocHeader;
    protected IntDocDetailType intDocDetail;
    protected IntDocSummaryType intDocSummary;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the intDocHeader property.
     * 
     * @return
     *     possible object is
     *     {@link IntDocHeaderType }
     *     
     */
    public IntDocHeaderType getIntDocHeader() {
        return intDocHeader;
    }

    /**
     * Sets the value of the intDocHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntDocHeaderType }
     *     
     */
    public void setIntDocHeader(IntDocHeaderType value) {
        this.intDocHeader = value;
    }

    /**
     * Gets the value of the intDocDetail property.
     * 
     * @return
     *     possible object is
     *     {@link IntDocDetailType }
     *     
     */
    public IntDocDetailType getIntDocDetail() {
        return intDocDetail;
    }

    /**
     * Sets the value of the intDocDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntDocDetailType }
     *     
     */
    public void setIntDocDetail(IntDocDetailType value) {
        this.intDocDetail = value;
    }

    /**
     * Gets the value of the intDocSummary property.
     * 
     * @return
     *     possible object is
     *     {@link IntDocSummaryType }
     *     
     */
    public IntDocSummaryType getIntDocSummary() {
        return intDocSummary;
    }

    /**
     * Sets the value of the intDocSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntDocSummaryType }
     *     
     */
    public void setIntDocSummary(IntDocSummaryType value) {
        this.intDocSummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
