//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.accountingunit;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import cz.stormware.schema.list.ListRequestType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.accountingunit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListAccountingUnit_QNAME = new QName("http://www.stormware.cz/schema/accountingunit.xsd", "listAccountingUnit");
    private final static QName _ListAccountingUnitRequest_QNAME = new QName("http://www.stormware.cz/schema/accountingunit.xsd", "listAccountingUnitRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.accountingunit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemAccountingUnitType }
     * 
     */
    public ItemAccountingUnitType createItemAccountingUnitType() {
        return new ItemAccountingUnitType();
    }

    /**
     * Create an instance of {@link ListAccountingUnitType }
     * 
     */
    public ListAccountingUnitType createListAccountingUnitType() {
        return new ListAccountingUnitType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountingUnitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/accountingunit.xsd", name = "listAccountingUnit")
    public JAXBElement<ListAccountingUnitType> createListAccountingUnit(ListAccountingUnitType value) {
        return new JAXBElement<ListAccountingUnitType>(_ListAccountingUnit_QNAME, ListAccountingUnitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/accountingunit.xsd", name = "listAccountingUnitRequest")
    public JAXBElement<ListRequestType> createListAccountingUnitRequest(ListRequestType value) {
        return new JAXBElement<ListRequestType>(_ListAccountingUnitRequest_QNAME, ListRequestType.class, null, value);
    }

}
