//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.accountingunit;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stateTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stateTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="naturalPerson"/>
 *     &lt;enumeration value="legalPerson"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stateTypeType")
@XmlEnum
public enum StateTypeType {


    /**
     * Fyzická osoba.
     * 
     */
    @XmlEnumValue("naturalPerson")
    NATURAL_PERSON("naturalPerson"),

    /**
     * Právnická osoba.
     * 
     */
    @XmlEnumValue("legalPerson")
    LEGAL_PERSON("legalPerson");
    private final String value;

    StateTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StateTypeType fromValue(String v) {
        for (StateTypeType c: StateTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
