//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.accountingunit;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unitTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="unitTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="singleEntry"/>
 *     &lt;enumeration value="doubleEntry"/>
 *     &lt;enumeration value="doubleEntryNonProfit"/>
 *     &lt;enumeration value="doubleEntryAllowance"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "unitTypeType")
@XmlEnum
public enum UnitTypeType {


    /**
     * Da\u0148ová evidence.
     * 
     */
    @XmlEnumValue("singleEntry")
    SINGLE_ENTRY("singleEntry"),

    /**
     * Podvojné ú\u010detnictví pro podnikatele.
     * 
     */
    @XmlEnumValue("doubleEntry")
    DOUBLE_ENTRY("doubleEntry"),

    /**
     * Podvojné ú\u010detnictví pro nevýd\u011ble\u010dné organizace.
     * 
     */
    @XmlEnumValue("doubleEntryNonProfit")
    DOUBLE_ENTRY_NON_PROFIT("doubleEntryNonProfit"),

    /**
     * Podvojné ú\u010detnictví pro p\u0159ísp\u011bvkové organizace.
     * 
     */
    @XmlEnumValue("doubleEntryAllowance")
    DOUBLE_ENTRY_ALLOWANCE("doubleEntryAllowance");
    private final String value;

    UnitTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitTypeType fromValue(String v) {
        for (UnitTypeType c: UnitTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
