//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.order;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import cz.stormware.schema.type.Address;
import cz.stormware.schema.type.Boolean;
import cz.stormware.schema.type.MyAddress;
import cz.stormware.schema.type.NumberType;
import cz.stormware.schema.type.ParameterDocType;
import cz.stormware.schema.type.PaymentType;
import cz.stormware.schema.type.RefType;


/**
 * <p>Java class for orderHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.stormware.cz/schema/type.xsd}idType" minOccurs="0"/>
 *         &lt;element name="orderType" type="{http://www.stormware.cz/schema/order.xsd}orderTypeType"/>
 *         &lt;element name="number" type="{http://www.stormware.cz/schema/type.xsd}numberType" minOccurs="0"/>
 *         &lt;element name="numberOrder" type="{http://www.stormware.cz/schema/type.xsd}documentNumberType" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dateDelivery" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dateFrom" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dateTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="text" type="{http://www.stormware.cz/schema/type.xsd}string240" minOccurs="0"/>
 *         &lt;element name="partnerIdentity" type="{http://www.stormware.cz/schema/type.xsd}address"/>
 *         &lt;element name="myIdentity" type="{http://www.stormware.cz/schema/type.xsd}myAddress" minOccurs="0"/>
 *         &lt;element name="paymentType" type="{http://www.stormware.cz/schema/type.xsd}paymentType" minOccurs="0"/>
 *         &lt;element name="priceLevel" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="isExecuted" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="isDelivered" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="isReserved" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="iShop" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="iShopName" type="{http://www.stormware.cz/schema/type.xsd}string35" minOccurs="0"/>
 *         &lt;element name="dateCancellation" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="centre" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="activity" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="contract" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parameter" type="{http://www.stormware.cz/schema/type.xsd}parameterDocType" maxOccurs="64" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderHeaderType", propOrder = {
    "id",
    "orderType",
    "number",
    "numberOrder",
    "date",
    "dateDelivery",
    "dateFrom",
    "dateTo",
    "text",
    "partnerIdentity",
    "myIdentity",
    "paymentType",
    "priceLevel",
    "isExecuted",
    "isDelivered",
    "isReserved",
    "iShop",
    "iShopName",
    "dateCancellation",
    "centre",
    "activity",
    "contract",
    "note",
    "intNote",
    "parameter"
})
public class OrderHeaderType {

    protected BigInteger id;
    @XmlElement(required = true)
    protected OrderTypeType orderType;
    protected NumberType number;
    protected String numberOrder;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateDelivery;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateFrom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateTo;
    protected String text;
    @XmlElement(required = true)
    protected Address partnerIdentity;
    protected MyAddress myIdentity;
    protected PaymentType paymentType;
    protected RefType priceLevel;
    protected Boolean isExecuted;
    protected Boolean isDelivered;
    protected Boolean isReserved;
    protected RefType iShop;
    protected String iShopName;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateCancellation;
    protected RefType centre;
    protected RefType activity;
    protected RefType contract;
    protected String note;
    protected String intNote;
    protected List<ParameterDocType> parameter;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link OrderTypeType }
     *     
     */
    public OrderTypeType getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderTypeType }
     *     
     */
    public void setOrderType(OrderTypeType value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumber(NumberType value) {
        this.number = value;
    }

    /**
     * Gets the value of the numberOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOrder() {
        return numberOrder;
    }

    /**
     * Sets the value of the numberOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOrder(String value) {
        this.numberOrder = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the dateDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateDelivery() {
        return dateDelivery;
    }

    /**
     * Sets the value of the dateDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateDelivery(XMLGregorianCalendar value) {
        this.dateDelivery = value;
    }

    /**
     * Gets the value of the dateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateFrom() {
        return dateFrom;
    }

    /**
     * Sets the value of the dateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateFrom(XMLGregorianCalendar value) {
        this.dateFrom = value;
    }

    /**
     * Gets the value of the dateTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTo() {
        return dateTo;
    }

    /**
     * Sets the value of the dateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTo(XMLGregorianCalendar value) {
        this.dateTo = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the partnerIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getPartnerIdentity() {
        return partnerIdentity;
    }

    /**
     * Sets the value of the partnerIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setPartnerIdentity(Address value) {
        this.partnerIdentity = value;
    }

    /**
     * Gets the value of the myIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link MyAddress }
     *     
     */
    public MyAddress getMyIdentity() {
        return myIdentity;
    }

    /**
     * Sets the value of the myIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MyAddress }
     *     
     */
    public void setMyIdentity(MyAddress value) {
        this.myIdentity = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentType }
     *     
     */
    public PaymentType getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentType }
     *     
     */
    public void setPaymentType(PaymentType value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the priceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getPriceLevel() {
        return priceLevel;
    }

    /**
     * Sets the value of the priceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setPriceLevel(RefType value) {
        this.priceLevel = value;
    }

    /**
     * Gets the value of the isExecuted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsExecuted() {
        return isExecuted;
    }

    /**
     * Sets the value of the isExecuted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsExecuted(Boolean value) {
        this.isExecuted = value;
    }

    /**
     * Gets the value of the isDelivered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsDelivered() {
        return isDelivered;
    }

    /**
     * Sets the value of the isDelivered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDelivered(Boolean value) {
        this.isDelivered = value;
    }

    /**
     * Gets the value of the isReserved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsReserved() {
        return isReserved;
    }

    /**
     * Sets the value of the isReserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReserved(Boolean value) {
        this.isReserved = value;
    }

    /**
     * Gets the value of the iShop property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getIShop() {
        return iShop;
    }

    /**
     * Sets the value of the iShop property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setIShop(RefType value) {
        this.iShop = value;
    }

    /**
     * Gets the value of the iShopName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIShopName() {
        return iShopName;
    }

    /**
     * Sets the value of the iShopName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIShopName(String value) {
        this.iShopName = value;
    }

    /**
     * Gets the value of the dateCancellation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCancellation() {
        return dateCancellation;
    }

    /**
     * Sets the value of the dateCancellation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCancellation(XMLGregorianCalendar value) {
        this.dateCancellation = value;
    }

    /**
     * Gets the value of the centre property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getCentre() {
        return centre;
    }

    /**
     * Sets the value of the centre property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setCentre(RefType value) {
        this.centre = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setActivity(RefType value) {
        this.activity = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setContract(RefType value) {
        this.contract = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the intNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntNote() {
        return intNote;
    }

    /**
     * Sets the value of the intNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntNote(String value) {
        this.intNote = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterDocType }
     * 
     * 
     */
    public List<ParameterDocType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterDocType>();
        }
        return this.parameter;
    }

}
