//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.order;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="orderTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="issuedOrder"/>
 *     &lt;enumeration value="receivedOrder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "orderTypeType")
@XmlEnum
public enum OrderTypeType {


    /**
     * Vydaná objednávka.
     * 
     */
    @XmlEnumValue("issuedOrder")
    ISSUED_ORDER("issuedOrder"),

    /**
     * P\u0159ijatá objednávka.
     * 
     */
    @XmlEnumValue("receivedOrder")
    RECEIVED_ORDER("receivedOrder");
    private final String value;

    OrderTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderTypeType fromValue(String v) {
        for (OrderTypeType c: OrderTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
