//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.prijemka;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.prijemka package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Prijemka_QNAME = new QName("http://www.stormware.cz/schema/prijemka.xsd", "prijemka");
    private final static QName _PrijemkaResponse_QNAME = new QName("http://www.stormware.cz/schema/prijemka.xsd", "prijemkaResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.prijemka
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrijemkaType }
     * 
     */
    public PrijemkaType createPrijemkaType() {
        return new PrijemkaType();
    }

    /**
     * Create an instance of {@link PrijemkaItemType }
     * 
     */
    public PrijemkaItemType createPrijemkaItemType() {
        return new PrijemkaItemType();
    }

    /**
     * Create an instance of {@link PrijemkaResponseType }
     * 
     */
    public PrijemkaResponseType createPrijemkaResponseType() {
        return new PrijemkaResponseType();
    }

    /**
     * Create an instance of {@link PrijemkaSummaryType }
     * 
     */
    public PrijemkaSummaryType createPrijemkaSummaryType() {
        return new PrijemkaSummaryType();
    }

    /**
     * Create an instance of {@link PrijemkaHeaderType }
     * 
     */
    public PrijemkaHeaderType createPrijemkaHeaderType() {
        return new PrijemkaHeaderType();
    }

    /**
     * Create an instance of {@link PrijemkaDetailType }
     * 
     */
    public PrijemkaDetailType createPrijemkaDetailType() {
        return new PrijemkaDetailType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrijemkaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/prijemka.xsd", name = "prijemka")
    public JAXBElement<PrijemkaType> createPrijemka(PrijemkaType value) {
        return new JAXBElement<PrijemkaType>(_Prijemka_QNAME, PrijemkaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrijemkaResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/prijemka.xsd", name = "prijemkaResponse")
    public JAXBElement<PrijemkaResponseType> createPrijemkaResponse(PrijemkaResponseType value) {
        return new JAXBElement<PrijemkaResponseType>(_PrijemkaResponse_QNAME, PrijemkaResponseType.class, null, value);
    }

}
