//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//


package cz.stormware.schema.addressbook;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import cz.stormware.schema.type.Address;
import cz.stormware.schema.type.Boolean;
import cz.stormware.schema.type.NumberType;
import cz.stormware.schema.type.ParameterDocType;
import cz.stormware.schema.type.PaymentType;
import cz.stormware.schema.type.RefAddressType;
import cz.stormware.schema.type.RefType;
import cz.stormware.schema.type.SexType;


/**
 * <p>Java class for addressbookHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressbookHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.stormware.cz/schema/type.xsd}idType" minOccurs="0"/>
 *         &lt;element name="identity" type="{http://www.stormware.cz/schema/type.xsd}address" minOccurs="0"/>
 *         &lt;element name="region" type="{http://www.stormware.cz/schema/type.xsd}string32" minOccurs="0"/>
 *         &lt;element name="phone" type="{http://www.stormware.cz/schema/type.xsd}string40" minOccurs="0"/>
 *         &lt;element name="mobil" type="{http://www.stormware.cz/schema/type.xsd}string24" minOccurs="0"/>
 *         &lt;element name="fax" type="{http://www.stormware.cz/schema/type.xsd}string24" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.stormware.cz/schema/type.xsd}string64" minOccurs="0"/>
 *         &lt;element name="web" type="{http://www.stormware.cz/schema/type.xsd}string32" minOccurs="0"/>
 *         &lt;element name="adGroup" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="adKey" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="credit" type="{http://www.stormware.cz/schema/type.xsd}currencyType" minOccurs="0"/>
 *         &lt;element name="priceIDS" type="{http://www.stormware.cz/schema/type.xsd}string10" minOccurs="0"/>
 *         &lt;element name="maturity" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="paymentType" type="{http://www.stormware.cz/schema/type.xsd}paymentType" minOccurs="0"/>
 *         &lt;element name="agreement" type="{http://www.stormware.cz/schema/type.xsd}string12" minOccurs="0"/>
 *         &lt;element name="number" type="{http://www.stormware.cz/schema/type.xsd}numberType" minOccurs="0"/>
 *         &lt;element name="ost1" type="{http://www.stormware.cz/schema/type.xsd}string8" minOccurs="0"/>
 *         &lt;element name="ost2" type="{http://www.stormware.cz/schema/type.xsd}string8" minOccurs="0"/>
 *         &lt;element name="function" type="{http://www.stormware.cz/schema/type.xsd}string32" minOccurs="0"/>
 *         &lt;element name="personalIdentificationNumber" type="{http://www.stormware.cz/schema/type.xsd}string11" minOccurs="0"/>
 *         &lt;element name="salutation" type="{http://www.stormware.cz/schema/type.xsd}string32" minOccurs="0"/>
 *         &lt;element name="sex" type="{http://www.stormware.cz/schema/type.xsd}sexType" minOccurs="0"/>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="p1" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="p2" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="p3" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="p4" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="p5" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="p6" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.stormware.cz/schema/type.xsd}string64" minOccurs="0"/>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duplicityFields" type="{http://www.stormware.cz/schema/addressbook.xsd}duplicityFieldsType" minOccurs="0"/>
 *         &lt;element name="centre" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="activity" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="contract" type="{http://www.stormware.cz/schema/type.xsd}refType" minOccurs="0"/>
 *         &lt;element name="parameter" type="{http://www.stormware.cz/schema/type.xsd}parameterDocType" maxOccurs="64" minOccurs="0"/>
 *         &lt;element name="refAddress" type="{http://www.stormware.cz/schema/type.xsd}refAddressType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressbookHeaderType", propOrder = {
    "id",
    "identity",
    "region",
    "phone",
    "mobil",
    "fax",
    "email",
    "web",
    "adGroup",
    "adKey",
    "credit",
    "priceIDS",
    "maturity",
    "paymentType",
    "agreement",
    "number",
    "ost1",
    "ost2",
    "function",
    "personalIdentificationNumber",
    "salutation",
    "sex",
    "dateOfBirth",
    "p1",
    "p2",
    "p3",
    "p4",
    "p5",
    "p6",
    "message",
    "note",
    "intNote",
    "duplicityFields",
    "centre",
    "activity",
    "contract",
    "parameter",
    "refAddress"
})
public class AddressbookHeaderType {

    protected BigInteger id;
    protected Address identity;
    protected String region;
    protected String phone;
    protected String mobil;
    protected String fax;
    protected String email;
    protected String web;
    protected String adGroup;
    protected String adKey;
    @XmlElement(defaultValue = "0")
    protected Double credit;
    protected String priceIDS;
    @XmlElement(defaultValue = "0")
    protected Short maturity;
    protected PaymentType paymentType;
    protected String agreement;
    protected NumberType number;
    protected String ost1;
    protected String ost2;
    protected String function;
    protected String personalIdentificationNumber;
    protected String salutation;
    protected SexType sex;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlElement(defaultValue = "false")
    protected Boolean p1;
    @XmlElement(defaultValue = "false")
    protected Boolean p2;
    @XmlElement(defaultValue = "false")
    protected Boolean p3;
    @XmlElement(defaultValue = "false")
    protected Boolean p4;
    @XmlElement(defaultValue = "false")
    protected Boolean p5;
    @XmlElement(defaultValue = "false")
    protected Boolean p6;
    protected String message;
    protected String note;
    protected String intNote;
    protected DuplicityFieldsType duplicityFields;
    protected RefType centre;
    protected RefType activity;
    protected RefType contract;
    protected List<ParameterDocType> parameter;
    protected RefAddressType refAddress;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setIdentity(Address value) {
        this.identity = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the mobil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobil() {
        return mobil;
    }

    /**
     * Sets the value of the mobil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobil(String value) {
        this.mobil = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the web property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeb() {
        return web;
    }

    /**
     * Sets the value of the web property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeb(String value) {
        this.web = value;
    }

    /**
     * Gets the value of the adGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdGroup() {
        return adGroup;
    }

    /**
     * Sets the value of the adGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdGroup(String value) {
        this.adGroup = value;
    }

    /**
     * Gets the value of the adKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdKey() {
        return adKey;
    }

    /**
     * Sets the value of the adKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdKey(String value) {
        this.adKey = value;
    }

    /**
     * Gets the value of the credit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCredit(Double value) {
        this.credit = value;
    }

    /**
     * Gets the value of the priceIDS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceIDS() {
        return priceIDS;
    }

    /**
     * Sets the value of the priceIDS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceIDS(String value) {
        this.priceIDS = value;
    }

    /**
     * Gets the value of the maturity property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMaturity() {
        return maturity;
    }

    /**
     * Sets the value of the maturity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMaturity(Short value) {
        this.maturity = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentType }
     *     
     */
    public PaymentType getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentType }
     *     
     */
    public void setPaymentType(PaymentType value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the agreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreement() {
        return agreement;
    }

    /**
     * Sets the value of the agreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreement(String value) {
        this.agreement = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumber(NumberType value) {
        this.number = value;
    }

    /**
     * Gets the value of the ost1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOst1() {
        return ost1;
    }

    /**
     * Sets the value of the ost1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOst1(String value) {
        this.ost1 = value;
    }

    /**
     * Gets the value of the ost2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOst2() {
        return ost2;
    }

    /**
     * Sets the value of the ost2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOst2(String value) {
        this.ost2 = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the personalIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalIdentificationNumber() {
        return personalIdentificationNumber;
    }

    /**
     * Sets the value of the personalIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalIdentificationNumber(String value) {
        this.personalIdentificationNumber = value;
    }

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutation(String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link SexType }
     *     
     */
    public SexType getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link SexType }
     *     
     */
    public void setSex(SexType value) {
        this.sex = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the p1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getP1() {
        return p1;
    }

    /**
     * Sets the value of the p1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setP1(Boolean value) {
        this.p1 = value;
    }

    /**
     * Gets the value of the p2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getP2() {
        return p2;
    }

    /**
     * Sets the value of the p2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setP2(Boolean value) {
        this.p2 = value;
    }

    /**
     * Gets the value of the p3 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getP3() {
        return p3;
    }

    /**
     * Sets the value of the p3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setP3(Boolean value) {
        this.p3 = value;
    }

    /**
     * Gets the value of the p4 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getP4() {
        return p4;
    }

    /**
     * Sets the value of the p4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setP4(Boolean value) {
        this.p4 = value;
    }

    /**
     * Gets the value of the p5 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getP5() {
        return p5;
    }

    /**
     * Sets the value of the p5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setP5(Boolean value) {
        this.p5 = value;
    }

    /**
     * Gets the value of the p6 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getP6() {
        return p6;
    }

    /**
     * Sets the value of the p6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setP6(Boolean value) {
        this.p6 = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the intNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntNote() {
        return intNote;
    }

    /**
     * Sets the value of the intNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntNote(String value) {
        this.intNote = value;
    }

    /**
     * Gets the value of the duplicityFields property.
     * 
     * @return
     *     possible object is
     *     {@link DuplicityFieldsType }
     *     
     */
    public DuplicityFieldsType getDuplicityFields() {
        return duplicityFields;
    }

    /**
     * Sets the value of the duplicityFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link DuplicityFieldsType }
     *     
     */
    public void setDuplicityFields(DuplicityFieldsType value) {
        this.duplicityFields = value;
    }

    /**
     * Gets the value of the centre property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getCentre() {
        return centre;
    }

    /**
     * Sets the value of the centre property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setCentre(RefType value) {
        this.centre = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setActivity(RefType value) {
        this.activity = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setContract(RefType value) {
        this.contract = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterDocType }
     * 
     * 
     */
    public List<ParameterDocType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterDocType>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the refAddress property.
     * 
     * @return
     *     possible object is
     *     {@link RefAddressType }
     *     
     */
    public RefAddressType getRefAddress() {
        return refAddress;
    }

    /**
     * Sets the value of the refAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefAddressType }
     *     
     */
    public void setRefAddress(RefAddressType value) {
        this.refAddress = value;
    }

}
