//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.stormware.cz/schema/addressbook.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cz.stormware.schema.addressbook;
