//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//


package cz.stormware.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for guaranteeTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="guaranteeTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="hour"/>
 *     &lt;enumeration value="day"/>
 *     &lt;enumeration value="month"/>
 *     &lt;enumeration value="year"/>
 *     &lt;enumeration value="life"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "guaranteeTypeType")
@XmlEnum
public enum GuaranteeTypeType {


    /**
     * Bez záruky.
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * Záruka je uvedena v hodinách.
     * 
     */
    @XmlEnumValue("hour")
    HOUR("hour"),

    /**
     * Záruka je uvedena v dnech.
     * 
     */
    @XmlEnumValue("day")
    DAY("day"),

    /**
     * Záruka je uvedena v m\u011bsících.
     * 
     */
    @XmlEnumValue("month")
    MONTH("month"),

    /**
     * Záruka je uvedena v rocích.
     * 
     */
    @XmlEnumValue("year")
    YEAR("year"),

    /**
     * Doživotní záruka.
     * 
     */
    @XmlEnumValue("life")
    LIFE("life");
    private final String value;

    GuaranteeTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GuaranteeTypeType fromValue(String v) {
        for (GuaranteeTypeType c: GuaranteeTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
