//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//


package cz.stormware.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeRoundingVAT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeRoundingVAT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="up2tenthEveryItem"/>
 *     &lt;enumeration value="up2tenthEveryRate"/>
 *     &lt;enumeration value="math2tenthEveryItem"/>
 *     &lt;enumeration value="math2halfEveryItem"/>
 *     &lt;enumeration value="math2tenthEveryRate"/>
 *     &lt;enumeration value="math2halfEveryRate"/>
 *     &lt;enumeration value="noneEveryRate"/>
 *     &lt;enumeration value="math2intEveryItem"/>
 *     &lt;enumeration value="math2intEveryRate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeRoundingVAT")
@XmlEnum
public enum TypeRoundingVAT {


    /**
     * "DPH nezaokrouhlovat", CZ po 1.1.2005 "P\u0159esn\u011b na halé\u0159e (DPH nezaokrouhlovat)."
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * "Zaokrouhlit DPH na každé položce", v CZ se nepoužívá po 1.1.2005.
     * 
     */
    @XmlEnumValue("up2tenthEveryItem")
    UP_2_TENTH_EVERY_ITEM("up2tenthEveryItem"),

    /**
     * "Zaokrouhlit sou\u010det DPH v každé sazb\u011b", v CZ se nepoužívá po 1.1.2005.
     * 
     */
    @XmlEnumValue("up2tenthEveryRate")
    UP_2_TENTH_EVERY_RATE("up2tenthEveryRate"),

    /**
     * "Matematicky zaokrouhlit na 10h". Používá se jen v CZ verzi.
     * 
     */
    @XmlEnumValue("math2tenthEveryItem")
    MATH_2_TENTH_EVERY_ITEM("math2tenthEveryItem"),

    /**
     * "Matematicky zaokrouhlit na 50h". Používá se jen v CZ verzi.
     * 
     */
    @XmlEnumValue("math2halfEveryItem")
    MATH_2_HALF_EVERY_ITEM("math2halfEveryItem"),

    /**
     * "Zaokr. DPH v každé sazb\u011b, mat. na 10h". Používá se jen v CZ verzi.
     * 
     */
    @XmlEnumValue("math2tenthEveryRate")
    MATH_2_TENTH_EVERY_RATE("math2tenthEveryRate"),

    /**
     * "Zaokr. DPH v každé sazb\u011b, mat. na 50h". Používá se jen v CZ verzi.
     * 
     */
    @XmlEnumValue("math2halfEveryRate")
    MATH_2_HALF_EVERY_RATE("math2halfEveryRate"),

    /**
     * "DPH v každé sazb\u011b nezaokrouhlovat". Používá se jen v CZ verzi.
     * 
     */
    @XmlEnumValue("noneEveryRate")
    NONE_EVERY_RATE("noneEveryRate"),

    /**
     * "Matematicky zaokrouhlit na koruny". Používá se jen v CZ verzi od 1.9.2008.
     * 
     */
    @XmlEnumValue("math2intEveryItem")
    MATH_2_INT_EVERY_ITEM("math2intEveryItem"),

    /**
     * "Zaokr. DPH v každé sazb\u011b, mat. na koruny". Používá se jen v CZ verzi od 1.9.2008.
     * 
     */
    @XmlEnumValue("math2intEveryRate")
    MATH_2_INT_EVERY_RATE("math2intEveryRate");
    private final String value;

    TypeRoundingVAT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeRoundingVAT fromValue(String v) {
        for (TypeRoundingVAT c: TypeRoundingVAT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
