//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import cz.stormware.schema.accountingunit.ListAccountingUnitType;
import cz.stormware.schema.addressbook.AddressbookResponseType;
import cz.stormware.schema.contract.ContractType;
import cz.stormware.schema.enquiry.EnquiryResponseType;
import cz.stormware.schema.intdoc.IntDocResponseType;
import cz.stormware.schema.invoice.InvoiceResponseType;
import cz.stormware.schema.list.CreateAccountingDoubleEntryResponseType;
import cz.stormware.schema.list.ListAccountType;
import cz.stormware.schema.list.ListAccountingDoubleEntryType;
import cz.stormware.schema.list.ListAccountingSingleEntryType;
import cz.stormware.schema.list.ListActivityType;
import cz.stormware.schema.list.ListAddressBookType;
import cz.stormware.schema.list.ListBalanceType;
import cz.stormware.schema.list.ListCashType;
import cz.stormware.schema.list.ListCentreType;
import cz.stormware.schema.list.ListEnquiryType;
import cz.stormware.schema.list.ListInvoiceType;
import cz.stormware.schema.list.ListNumericSeriesType;
import cz.stormware.schema.list.ListOfferType;
import cz.stormware.schema.list.ListOrderType;
import cz.stormware.schema.list.ListParameterType;
import cz.stormware.schema.list.ListPrijemkaType;
import cz.stormware.schema.list.ListSellingPriceType;
import cz.stormware.schema.list.ListStockType;
import cz.stormware.schema.list.ListStorageType;
import cz.stormware.schema.list.ListUserCodePackType;
import cz.stormware.schema.list.ListVydejkaType;
import cz.stormware.schema.offer.OfferResponseType;
import cz.stormware.schema.order.OrderResponseType;
import cz.stormware.schema.parameter.ParameterItemResponseType;
import cz.stormware.schema.prevodka.PrevodkaResponseType;
import cz.stormware.schema.prijemka.PrijemkaResponseType;
import cz.stormware.schema.prodejka.ProdejkaResponseType;
import cz.stormware.schema.stock.StockItemResponseType;
import cz.stormware.schema.type.StavType2;
import cz.stormware.schema.voucher.VoucherResponseType;
import cz.stormware.schema.vydejka.VydejkaResponseType;
import cz.stormware.schema.vyroba.VyrobaResponseType;


/**
 * <p>Java class for responsePackItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responsePackItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element ref="{http://www.stormware.cz/schema/invoice.xsd}invoiceResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/voucher.xsd}voucherResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/addressbook.xsd}addressbookResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/intDoc.xsd}intDocResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/vydejka.xsd}vydejkaResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/prijemka.xsd}prijemkaResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/prodejka.xsd}prodejkaResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/stock.xsd}stockItemResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/order.xsd}orderResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/enquiry.xsd}enquiryResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/offer.xsd}offerResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/vyroba.xsd}vyrobaResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/prevodka.xsd}prevodkaResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/parameter.xsd}parameterItemResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/contract.xsd}contract"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listCentre"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listActivity"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listContract"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listCash"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listAccountingSingleEntry"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listAccountingDoubleEntry"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listAccount"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listStorage"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listSellingPrice"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listNumericSeries"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}createAccountingDoubleEntryResponse"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/accountingunit.xsd}listAccountingUnit"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listStock"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listInvoice"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listAddressBook"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listOrder"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listEnquiry"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listOffer"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listParameter"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listUserCodePack"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listVydejka"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listPrijemka"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list.xsd}listBalance"/>
 *         &lt;element ref="{http://www.stormware.cz/schema/list_2.xsd}listContract"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" use="required" type="{http://www.stormware.cz/schema/type.xsd}stavType2" />
 *       &lt;attribute name="note" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responsePackItemType", propOrder = {
    "content"
})
public class ResponsePackItemType {

    @XmlElementRefs({
        @XmlElementRef(name = "listAddressBook", namespace = "http://www.stormware.cz/schema/list.xsd", type = JAXBElement.class)
//        @XmlElementRef(name = "listInvoice", namespace = "http://www.stormware.cz/schema/list.xsd", type = JAXBElement.class),
    })
    protected List<JAXBElement<?>> content;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected StavType2 state;
    @XmlAttribute
    protected String note;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "ListContract" is used by two different parts of a schema. See: 
     * line 113 of file:/H:/desktop/sis3/modules/sis-sync/src/main/resources/xsd/response.xsd
     * line 92 of file:/H:/desktop/sis3/modules/sis-sync/src/main/resources/xsd/response.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ParameterItemResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListCentreType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListAddressBookType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListPrijemkaType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListUserCodePackType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListBalanceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListEnquiryType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListStorageType }{@code >}
     * {@link JAXBElement }{@code <}{@link VydejkaResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link InvoiceResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link CreateAccountingDoubleEntryResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListAccountingSingleEntryType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListNumericSeriesType }{@code >}
     * {@link JAXBElement }{@code <}{@link cz.stormware.schema.list_2.ListContractType }{@code >}
     * {@link JAXBElement }{@code <}{@link ProdejkaResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListActivityType }{@code >}
     * {@link JAXBElement }{@code <}{@link VyrobaResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ContractType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListSellingPriceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListOrderType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListOfferType }{@code >}
     * {@link JAXBElement }{@code <}{@link PrevodkaResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListInvoiceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListAccountingDoubleEntryType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListCashType }{@code >}
     * {@link JAXBElement }{@code <}{@link cz.stormware.schema.list.ListContractType }{@code >}
     * {@link JAXBElement }{@code <}{@link PrijemkaResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link IntDocResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListAccountType }{@code >}
     * {@link JAXBElement }{@code <}{@link OfferResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListVydejkaType }{@code >}
     * {@link JAXBElement }{@code <}{@link StockItemResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link VoucherResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link EnquiryResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListParameterType }{@code >}
     * {@link JAXBElement }{@code <}{@link AddressbookResponseType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListAccountingUnitType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListStockType }{@code >}
     * {@link JAXBElement }{@code <}{@link OrderResponseType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StavType2 }
     *     
     */
    public StavType2 getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavType2 }
     *     
     */
    public void setState(StavType2 value) {
        this.state = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

}
