//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.parameter;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import cz.stormware.schema.type.ParameterAgendaFormType;


/**
 * Seznam definic volitelných parametr\u016f.
 * 
 * <p>Java class for formItemListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formItemListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ctrlDef" type="{http://www.stormware.cz/schema/parameter.xsd}ctrlDefType" maxOccurs="255" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="formAgenda" type="{http://www.stormware.cz/schema/type.xsd}parameterAgendaFormType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formItemListType", propOrder = {
    "ctrlDef"
})
public class FormItemListType {

    protected List<CtrlDefType> ctrlDef;
    @XmlAttribute
    protected ParameterAgendaFormType formAgenda;

    /**
     * Gets the value of the ctrlDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ctrlDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCtrlDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtrlDefType }
     * 
     * 
     */
    public List<CtrlDefType> getCtrlDef() {
        if (ctrlDef == null) {
            ctrlDef = new ArrayList<CtrlDefType>();
        }
        return this.ctrlDef;
    }

    /**
     * Gets the value of the formAgenda property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterAgendaFormType }
     *     
     */
    public ParameterAgendaFormType getFormAgenda() {
        return formAgenda;
    }

    /**
     * Sets the value of the formAgenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterAgendaFormType }
     *     
     */
    public void setFormAgenda(ParameterAgendaFormType value) {
        this.formAgenda = value;
    }

}
