//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.prodejka;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for prodejkaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prodejkaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prodejkaHeader" type="{http://www.stormware.cz/schema/prodejka.xsd}prodejkaHeaderType"/>
 *         &lt;element name="prodejkaDetail" type="{http://www.stormware.cz/schema/prodejka.xsd}prodejkaDetailType" minOccurs="0"/>
 *         &lt;element name="prodejkaSummary" type="{http://www.stormware.cz/schema/prodejka.xsd}prodejkaSummaryType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.stormware.cz/schema/prodejka.xsd}proVersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prodejkaType", propOrder = {
    "prodejkaHeader",
    "prodejkaDetail",
    "prodejkaSummary"
})
public class ProdejkaType {

    @XmlElement(required = true)
    protected ProdejkaHeaderType prodejkaHeader;
    protected ProdejkaDetailType prodejkaDetail;
    protected ProdejkaSummaryType prodejkaSummary;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the prodejkaHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ProdejkaHeaderType }
     *     
     */
    public ProdejkaHeaderType getProdejkaHeader() {
        return prodejkaHeader;
    }

    /**
     * Sets the value of the prodejkaHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdejkaHeaderType }
     *     
     */
    public void setProdejkaHeader(ProdejkaHeaderType value) {
        this.prodejkaHeader = value;
    }

    /**
     * Gets the value of the prodejkaDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ProdejkaDetailType }
     *     
     */
    public ProdejkaDetailType getProdejkaDetail() {
        return prodejkaDetail;
    }

    /**
     * Sets the value of the prodejkaDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdejkaDetailType }
     *     
     */
    public void setProdejkaDetail(ProdejkaDetailType value) {
        this.prodejkaDetail = value;
    }

    /**
     * Gets the value of the prodejkaSummary property.
     * 
     * @return
     *     possible object is
     *     {@link ProdejkaSummaryType }
     *     
     */
    public ProdejkaSummaryType getProdejkaSummary() {
        return prodejkaSummary;
    }

    /**
     * Sets the value of the prodejkaSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdejkaSummaryType }
     *     
     */
    public void setProdejkaSummary(ProdejkaSummaryType value) {
        this.prodejkaSummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
