//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.stock;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classOfStockType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="classOfStockType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="material"/>
 *     &lt;enumeration value="goods"/>
 *     &lt;enumeration value="workInProgress"/>
 *     &lt;enumeration value="semiproducts"/>
 *     &lt;enumeration value="products"/>
 *     &lt;enumeration value="animals"/>
 *     &lt;enumeration value="materialOfOwnProduction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "classOfStockType")
@XmlEnum
public enum ClassOfStockType {


    /**
     * Materiál.
     * 
     */
    @XmlEnumValue("material")
    MATERIAL("material"),

    /**
     * Zboží.
     * 
     */
    @XmlEnumValue("goods")
    GOODS("goods"),

    /**
     * Nedokon\u010dená výroba.
     * 
     */
    @XmlEnumValue("workInProgress")
    WORK_IN_PROGRESS("workInProgress"),

    /**
     * Polotovary.
     * 
     */
    @XmlEnumValue("semiproducts")
    SEMIPRODUCTS("semiproducts"),

    /**
     * Výrobky.
     * 
     */
    @XmlEnumValue("products")
    PRODUCTS("products"),

    /**
     * Zví\u0159ata.
     * 
     */
    @XmlEnumValue("animals")
    ANIMALS("animals"),

    /**
     * Materiál vl. výroby.
     * 
     */
    @XmlEnumValue("materialOfOwnProduction")
    MATERIAL_OF_OWN_PRODUCTION("materialOfOwnProduction");
    private final String value;

    ClassOfStockType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassOfStockType fromValue(String v) {
        for (ClassOfStockType c: ClassOfStockType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
