//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.stock;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stockType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stockType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stockHeader" type="{http://www.stormware.cz/schema/stock.xsd}stockHeaderType"/>
 *         &lt;element name="stockDetail" type="{http://www.stormware.cz/schema/stock.xsd}stockDetailType" minOccurs="0"/>
 *         &lt;element name="stockAttach" type="{http://www.stormware.cz/schema/stock.xsd}stockAttachType" minOccurs="0"/>
 *         &lt;element name="stockSerialNumber" type="{http://www.stormware.cz/schema/stock.xsd}stockSerialNumberType" minOccurs="0"/>
 *         &lt;element name="stockPriceItem" type="{http://www.stormware.cz/schema/stock.xsd}stockPriceItemType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.stormware.cz/schema/stock.xsd}stkVersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stockType", propOrder = {
    "stockHeader",
    "stockDetail",
    "stockAttach",
    "stockSerialNumber",
    "stockPriceItem"
})
public class StockType {

    @XmlElement(required = true)
    protected StockHeaderType stockHeader;
    protected StockDetailType stockDetail;
    protected StockAttachType stockAttach;
    protected StockSerialNumberType stockSerialNumber;
    protected StockPriceItemType stockPriceItem;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the stockHeader property.
     * 
     * @return
     *     possible object is
     *     {@link StockHeaderType }
     *     
     */
    public StockHeaderType getStockHeader() {
        return stockHeader;
    }

    /**
     * Sets the value of the stockHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockHeaderType }
     *     
     */
    public void setStockHeader(StockHeaderType value) {
        this.stockHeader = value;
    }

    /**
     * Gets the value of the stockDetail property.
     * 
     * @return
     *     possible object is
     *     {@link StockDetailType }
     *     
     */
    public StockDetailType getStockDetail() {
        return stockDetail;
    }

    /**
     * Sets the value of the stockDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockDetailType }
     *     
     */
    public void setStockDetail(StockDetailType value) {
        this.stockDetail = value;
    }

    /**
     * Gets the value of the stockAttach property.
     * 
     * @return
     *     possible object is
     *     {@link StockAttachType }
     *     
     */
    public StockAttachType getStockAttach() {
        return stockAttach;
    }

    /**
     * Sets the value of the stockAttach property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockAttachType }
     *     
     */
    public void setStockAttach(StockAttachType value) {
        this.stockAttach = value;
    }

    /**
     * Gets the value of the stockSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link StockSerialNumberType }
     *     
     */
    public StockSerialNumberType getStockSerialNumber() {
        return stockSerialNumber;
    }

    /**
     * Sets the value of the stockSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockSerialNumberType }
     *     
     */
    public void setStockSerialNumber(StockSerialNumberType value) {
        this.stockSerialNumber = value;
    }

    /**
     * Gets the value of the stockPriceItem property.
     * 
     * @return
     *     possible object is
     *     {@link StockPriceItemType }
     *     
     */
    public StockPriceItemType getStockPriceItem() {
        return stockPriceItem;
    }

    /**
     * Sets the value of the stockPriceItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockPriceItemType }
     *     
     */
    public void setStockPriceItem(StockPriceItemType value) {
        this.stockPriceItem = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
