//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.list;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listContractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listContractType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.stormware.cz/schema/list.xsd}listVersionType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="itemContract" type="{http://www.stormware.cz/schema/list.xsd}itemContractType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listContractType", propOrder = {
    "itemContract"
})
public class ListContractType
    extends ListVersionType
{

    protected List<ItemContractType> itemContract;

    /**
     * Gets the value of the itemContract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemContract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemContract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemContractType }
     * 
     * 
     */
    public List<ItemContractType> getItemContract() {
        if (itemContract == null) {
            itemContract = new ArrayList<ItemContractType>();
        }
        return this.itemContract;
    }

}
