//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.list;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listSellingPriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listSellingPriceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.stormware.cz/schema/list.xsd}listVersionType">
 *       &lt;choice>
 *         &lt;element name="itemSellingPrice" type="{http://www.stormware.cz/schema/list.xsd}itemSellingPriceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listSellingPriceType", propOrder = {
    "itemSellingPrice"
})
public class ListSellingPriceType
    extends ListVersionType
{

    protected List<ItemSellingPriceType> itemSellingPrice;

    /**
     * Gets the value of the itemSellingPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemSellingPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemSellingPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemSellingPriceType }
     * 
     * 
     */
    public List<ItemSellingPriceType> getItemSellingPrice() {
        if (itemSellingPrice == null) {
            itemSellingPrice = new ArrayList<ItemSellingPriceType>();
        }
        return this.itemSellingPrice;
    }

}
