//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//


package cz.stormware.schema.list;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listAddressBookRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listAddressBookRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="requestAddressBook" type="{http://www.stormware.cz/schema/list.xsd}requestAddressBookType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.stormware.cz/schema/list.xsd}listAddressBookRequestVerType" />
 *       &lt;attribute name="addressBookVersion" use="required" type="{http://www.stormware.cz/schema/addressbook.xsd}adbVersionType" />
 *       &lt;attribute name="extSystem" type="{http://www.stormware.cz/schema/type.xsd}string64" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listAddressBookRequestType", propOrder = {
    "requestAddressBook"
})
public class ListAddressBookRequestType {

    @XmlElement(required = true)
    protected List<RequestAddressBookType> requestAddressBook;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute(required = true)
    protected String addressBookVersion;
    @XmlAttribute
    protected String extSystem;

    /**
     * Gets the value of the requestAddressBook property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestAddressBook property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestAddressBook().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestAddressBookType }
     * 
     * 
     */
    public List<RequestAddressBookType> getRequestAddressBook() {
        if (requestAddressBook == null) {
            requestAddressBook = new ArrayList<RequestAddressBookType>();
        }
        return this.requestAddressBook;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the addressBookVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressBookVersion() {
        return addressBookVersion;
    }

    /**
     * Sets the value of the addressBookVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressBookVersion(String value) {
        this.addressBookVersion = value;
    }

    /**
     * Gets the value of the extSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtSystem() {
        return extSystem;
    }

    /**
     * Sets the value of the extSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtSystem(String value) {
        this.extSystem = value;
    }

}
