//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.list;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listIntParamRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listIntParamRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="requestIntParam" type="{http://www.stormware.cz/schema/list.xsd}requestIntParamType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.stormware.cz/schema/list.xsd}listIntParamRequestVerType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listIntParamRequestType", propOrder = {
    "requestIntParam"
})
public class ListIntParamRequestType {

    protected RequestIntParamType requestIntParam;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the requestIntParam property.
     * 
     * @return
     *     possible object is
     *     {@link RequestIntParamType }
     *     
     */
    public RequestIntParamType getRequestIntParam() {
        return requestIntParam;
    }

    /**
     * Sets the value of the requestIntParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestIntParamType }
     *     
     */
    public void setRequestIntParam(RequestIntParamType value) {
        this.requestIntParam = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
