//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.list;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listRequestAgendasType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listRequestAgendasType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.stormware.cz/schema/list.xsd}listRequestType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="agendas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="agenda" type="{http://www.stormware.cz/schema/list.xsd}agendaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listRequestAgendasType", propOrder = {
    "agendas"
})
public class ListRequestAgendasType
    extends ListRequestType
{

    protected ListRequestAgendasType.Agendas agendas;

    /**
     * Gets the value of the agendas property.
     * 
     * @return
     *     possible object is
     *     {@link ListRequestAgendasType.Agendas }
     *     
     */
    public ListRequestAgendasType.Agendas getAgendas() {
        return agendas;
    }

    /**
     * Sets the value of the agendas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListRequestAgendasType.Agendas }
     *     
     */
    public void setAgendas(ListRequestAgendasType.Agendas value) {
        this.agendas = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="agenda" type="{http://www.stormware.cz/schema/list.xsd}agendaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agenda"
    })
    public static class Agendas {

        protected List<AgendaType> agenda;

        /**
         * Gets the value of the agenda property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the agenda property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAgenda().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AgendaType }
         * 
         * 
         */
        public List<AgendaType> getAgenda() {
            if (agenda == null) {
                agenda = new ArrayList<AgendaType>();
            }
            return this.agenda;
        }

    }

}
