//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.list;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.list package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListAccount_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAccount");
    private final static QName _CreateAccountingDoubleEntry_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "createAccountingDoubleEntry");
    private final static QName _ListOfferRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listOfferRequest");
    private final static QName _ListCategoryRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listCategoryRequest");
    private final static QName _ListStorage_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listStorage");
    private final static QName _ListUserCodePack_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listUserCodePack");
    private final static QName _ListCategory_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listCategory");
    private final static QName _ListEnquiryRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listEnquiryRequest");
    private final static QName _ListIntParam_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listIntParam");
    private final static QName _ListPrijemkaRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listPrijemkaRequest");
    private final static QName _ListCashRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listCashRequest");
    private final static QName _ListStock_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listStock");
    private final static QName _ListContract_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listContract");
    private final static QName _ListBalanceRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listBalanceRequest");
    private final static QName _ListActivity_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listActivity");
    private final static QName _ListAddressBookRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAddressBookRequest");
    private final static QName _ListBalance_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listBalance");
    private final static QName _ListInvoice_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listInvoice");
    private final static QName _ListSellingPriceRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listSellingPriceRequest");
    private final static QName _ListPrijemka_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listPrijemka");
    private final static QName _ListOffer_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listOffer");
    private final static QName _ListCentreRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listCentreRequest");
    private final static QName _ListAddressBook_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAddressBook");
    private final static QName _ListNumericSeriesRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listNumericSeriesRequest");
    private final static QName _ListParameterRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listParameterRequest");
    private final static QName _ListStorageRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listStorageRequest");
    private final static QName _ListAccountingSingleEntryRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAccountingSingleEntryRequest");
    private final static QName _ListVydejka_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listVydejka");
    private final static QName _ListAccountingDoubleEntryRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAccountingDoubleEntryRequest");
    private final static QName _ListContractRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listContractRequest");
    private final static QName _ListParameter_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listParameter");
    private final static QName _ListOrderRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listOrderRequest");
    private final static QName _ListActivityRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listActivityRequest");
    private final static QName _ListAccountRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAccountRequest");
    private final static QName _ListOrder_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listOrder");
    private final static QName _ListInvoiceRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listInvoiceRequest");
    private final static QName _ListAccountingSingleEntry_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAccountingSingleEntry");
    private final static QName _CreateAccountingDoubleEntryResponse_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "createAccountingDoubleEntryResponse");
    private final static QName _ListUserCode_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listUserCode");
    private final static QName _ListIntParamRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listIntParamRequest");
    private final static QName _ListNumericSeries_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listNumericSeries");
    private final static QName _ListUserCodeRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listUserCodeRequest");
    private final static QName _ListCentre_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listCentre");
    private final static QName _ListCash_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listCash");
    private final static QName _ListEnquiry_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listEnquiry");
    private final static QName _ListAccountingDoubleEntry_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAccountingDoubleEntry");
    private final static QName _ListSellingPrice_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listSellingPrice");
    private final static QName _ListVydejkaRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listVydejkaRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.list
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestAddressBookType }
     * 
     */
    public RequestAddressBookType createRequestAddressBookType() {
        return new RequestAddressBookType();
    }

    /**
     * Create an instance of {@link ListPrijemkaRequestType }
     * 
     */
    public ListPrijemkaRequestType createListPrijemkaRequestType() {
        return new ListPrijemkaRequestType();
    }

    /**
     * Create an instance of {@link ListOrderRequestType }
     * 
     */
    public ListOrderRequestType createListOrderRequestType() {
        return new ListOrderRequestType();
    }

    /**
     * Create an instance of {@link ListCashType }
     * 
     */
    public ListCashType createListCashType() {
        return new ListCashType();
    }

    /**
     * Create an instance of {@link ListPrijemkaType }
     * 
     */
    public ListPrijemkaType createListPrijemkaType() {
        return new ListPrijemkaType();
    }

    /**
     * Create an instance of {@link ListInvoiceType }
     * 
     */
    public ListInvoiceType createListInvoiceType() {
        return new ListInvoiceType();
    }

    /**
     * Create an instance of {@link ListStorageType }
     * 
     */
    public ListStorageType createListStorageType() {
        return new ListStorageType();
    }

    /**
     * Create an instance of {@link RequestEnquiryType }
     * 
     */
    public RequestEnquiryType createRequestEnquiryType() {
        return new RequestEnquiryType();
    }

    /**
     * Create an instance of {@link ListAccountingSingleEntryType }
     * 
     */
    public ListAccountingSingleEntryType createListAccountingSingleEntryType() {
        return new ListAccountingSingleEntryType();
    }

    /**
     * Create an instance of {@link ListOfferRequestType }
     * 
     */
    public ListOfferRequestType createListOfferRequestType() {
        return new ListOfferRequestType();
    }

    /**
     * Create an instance of {@link ListRequestAgendasType }
     * 
     */
    public ListRequestAgendasType createListRequestAgendasType() {
        return new ListRequestAgendasType();
    }

    /**
     * Create an instance of {@link ListAccountingDoubleEntryType }
     * 
     */
    public ListAccountingDoubleEntryType createListAccountingDoubleEntryType() {
        return new ListAccountingDoubleEntryType();
    }

    /**
     * Create an instance of {@link RequestUserCodeType }
     * 
     */
    public RequestUserCodeType createRequestUserCodeType() {
        return new RequestUserCodeType();
    }

    /**
     * Create an instance of {@link ListSellingPriceType }
     * 
     */
    public ListSellingPriceType createListSellingPriceType() {
        return new ListSellingPriceType();
    }

    /**
     * Create an instance of {@link ItemNumericSeriesType }
     * 
     */
    public ItemNumericSeriesType createItemNumericSeriesType() {
        return new ItemNumericSeriesType();
    }

    /**
     * Create an instance of {@link ListCentreType }
     * 
     */
    public ListCentreType createListCentreType() {
        return new ListCentreType();
    }

    /**
     * Create an instance of {@link RequestInvoiceType }
     * 
     */
    public RequestInvoiceType createRequestInvoiceType() {
        return new RequestInvoiceType();
    }

    /**
     * Create an instance of {@link ListAddressBookType }
     * 
     */
    public ListAddressBookType createListAddressBookType() {
        return new ListAddressBookType();
    }

    /**
     * Create an instance of {@link CreateAccountingType }
     * 
     */
    public CreateAccountingType createCreateAccountingType() {
        return new CreateAccountingType();
    }

    /**
     * Create an instance of {@link FilterFieldsType }
     * 
     */
    public FilterFieldsType createFilterFieldsType() {
        return new FilterFieldsType();
    }

    /**
     * Create an instance of {@link CreateAccountingDoubleEntryType }
     * 
     */
    public CreateAccountingDoubleEntryType createCreateAccountingDoubleEntryType() {
        return new CreateAccountingDoubleEntryType();
    }

    /**
     * Create an instance of {@link ListIntParamType }
     * 
     */
    public ListIntParamType createListIntParamType() {
        return new ListIntParamType();
    }

    /**
     * Create an instance of {@link ListCategoryRequestType }
     * 
     */
    public ListCategoryRequestType createListCategoryRequestType() {
        return new ListCategoryRequestType();
    }

    /**
     * Create an instance of {@link ListRequestStoresType.Stores }
     * 
     */
    public ListRequestStoresType.Stores createListRequestStoresTypeStores() {
        return new ListRequestStoresType.Stores();
    }

    /**
     * Create an instance of {@link ListOrderType }
     * 
     */
    public ListOrderType createListOrderType() {
        return new ListOrderType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link CreateAccountingResponseType }
     * 
     */
    public CreateAccountingResponseType createCreateAccountingResponseType() {
        return new CreateAccountingResponseType();
    }

    /**
     * Create an instance of {@link ListContractType }
     * 
     */
    public ListContractType createListContractType() {
        return new ListContractType();
    }

    /**
     * Create an instance of {@link ListInvoiceRequestType }
     * 
     */
    public ListInvoiceRequestType createListInvoiceRequestType() {
        return new ListInvoiceRequestType();
    }

    /**
     * Create an instance of {@link ListStockType }
     * 
     */
    public ListStockType createListStockType() {
        return new ListStockType();
    }

    /**
     * Create an instance of {@link ListUserCodePackType }
     * 
     */
    public ListUserCodePackType createListUserCodePackType() {
        return new ListUserCodePackType();
    }

    /**
     * Create an instance of {@link ListRequestAgendasType.Agendas }
     * 
     */
    public ListRequestAgendasType.Agendas createListRequestAgendasTypeAgendas() {
        return new ListRequestAgendasType.Agendas();
    }

    /**
     * Create an instance of {@link ItemCashType }
     * 
     */
    public ItemCashType createItemCashType() {
        return new ItemCashType();
    }

    /**
     * Create an instance of {@link ListUserCodeRequestType }
     * 
     */
    public ListUserCodeRequestType createListUserCodeRequestType() {
        return new ListUserCodeRequestType();
    }

    /**
     * Create an instance of {@link ItemAccountingTypeDoubleEntry }
     * 
     */
    public ItemAccountingTypeDoubleEntry createItemAccountingTypeDoubleEntry() {
        return new ItemAccountingTypeDoubleEntry();
    }

    /**
     * Create an instance of {@link RequestVydejkaType }
     * 
     */
    public RequestVydejkaType createRequestVydejkaType() {
        return new RequestVydejkaType();
    }

    /**
     * Create an instance of {@link ListOfferType }
     * 
     */
    public ListOfferType createListOfferType() {
        return new ListOfferType();
    }

    /**
     * Create an instance of {@link ListNumericSeriesType }
     * 
     */
    public ListNumericSeriesType createListNumericSeriesType() {
        return new ListNumericSeriesType();
    }

    /**
     * Create an instance of {@link ItemSellingPriceType }
     * 
     */
    public ItemSellingPriceType createItemSellingPriceType() {
        return new ItemSellingPriceType();
    }

    /**
     * Create an instance of {@link ListIntParamRequestType }
     * 
     */
    public ListIntParamRequestType createListIntParamRequestType() {
        return new ListIntParamRequestType();
    }

    /**
     * Create an instance of {@link ListBalanceType }
     * 
     */
    public ListBalanceType createListBalanceType() {
        return new ListBalanceType();
    }

    /**
     * Create an instance of {@link ListVersionType }
     * 
     */
    public ListVersionType createListVersionType() {
        return new ListVersionType();
    }

    /**
     * Create an instance of {@link SelectedIcoType }
     * 
     */
    public SelectedIcoType createSelectedIcoType() {
        return new SelectedIcoType();
    }

    /**
     * Create an instance of {@link ItemAccountingTypeSingleEntry }
     * 
     */
    public ItemAccountingTypeSingleEntry createItemAccountingTypeSingleEntry() {
        return new ItemAccountingTypeSingleEntry();
    }

    /**
     * Create an instance of {@link RequestCategoryType }
     * 
     */
    public RequestCategoryType createRequestCategoryType() {
        return new RequestCategoryType();
    }

    /**
     * Create an instance of {@link ListActivityType }
     * 
     */
    public ListActivityType createListActivityType() {
        return new ListActivityType();
    }

    /**
     * Create an instance of {@link SelectedNumbersType }
     * 
     */
    public SelectedNumbersType createSelectedNumbersType() {
        return new SelectedNumbersType();
    }

    /**
     * Create an instance of {@link ListCategoryType }
     * 
     */
    public ListCategoryType createListCategoryType() {
        return new ListCategoryType();
    }

    /**
     * Create an instance of {@link RequestPrijemkaType }
     * 
     */
    public RequestPrijemkaType createRequestPrijemkaType() {
        return new RequestPrijemkaType();
    }

    /**
     * Create an instance of {@link RequestIntParamType }
     * 
     */
    public RequestIntParamType createRequestIntParamType() {
        return new RequestIntParamType();
    }

    /**
     * Create an instance of {@link ListEnquiryType }
     * 
     */
    public ListEnquiryType createListEnquiryType() {
        return new ListEnquiryType();
    }

    /**
     * Create an instance of {@link ListRequestType }
     * 
     */
    public ListRequestType createListRequestType() {
        return new ListRequestType();
    }

    /**
     * Create an instance of {@link ListAddressBookRequestType }
     * 
     */
    public ListAddressBookRequestType createListAddressBookRequestType() {
        return new ListAddressBookRequestType();
    }

    /**
     * Create an instance of {@link RequestOrderType }
     * 
     */
    public RequestOrderType createRequestOrderType() {
        return new RequestOrderType();
    }

    /**
     * Create an instance of {@link ListParameterRequestType }
     * 
     */
    public ListParameterRequestType createListParameterRequestType() {
        return new ListParameterRequestType();
    }

    /**
     * Create an instance of {@link ListEnquiryRequestType }
     * 
     */
    public ListEnquiryRequestType createListEnquiryRequestType() {
        return new ListEnquiryRequestType();
    }

    /**
     * Create an instance of {@link ListParameterType }
     * 
     */
    public ListParameterType createListParameterType() {
        return new ListParameterType();
    }

    /**
     * Create an instance of {@link ListBalanceRequestType }
     * 
     */
    public ListBalanceRequestType createListBalanceRequestType() {
        return new ListBalanceRequestType();
    }

    /**
     * Create an instance of {@link ListRequestStoresType }
     * 
     */
    public ListRequestStoresType createListRequestStoresType() {
        return new ListRequestStoresType();
    }

    /**
     * Create an instance of {@link ListVydejkaRequestType }
     * 
     */
    public ListVydejkaRequestType createListVydejkaRequestType() {
        return new ListVydejkaRequestType();
    }

    /**
     * Create an instance of {@link ListAccountType }
     * 
     */
    public ListAccountType createListAccountType() {
        return new ListAccountType();
    }

    /**
     * Create an instance of {@link RequestBalanceType }
     * 
     */
    public RequestBalanceType createRequestBalanceType() {
        return new RequestBalanceType();
    }

    /**
     * Create an instance of {@link SelectedCompanysType }
     * 
     */
    public SelectedCompanysType createSelectedCompanysType() {
        return new SelectedCompanysType();
    }

    /**
     * Create an instance of {@link ItemStorageType }
     * 
     */
    public ItemStorageType createItemStorageType() {
        return new ItemStorageType();
    }

    /**
     * Create an instance of {@link CreateAccountingDoubleEntryResponseType }
     * 
     */
    public CreateAccountingDoubleEntryResponseType createCreateAccountingDoubleEntryResponseType() {
        return new CreateAccountingDoubleEntryResponseType();
    }

    /**
     * Create an instance of {@link ItemAccountType }
     * 
     */
    public ItemAccountType createItemAccountType() {
        return new ItemAccountType();
    }

    /**
     * Create an instance of {@link RequestOfferType }
     * 
     */
    public RequestOfferType createRequestOfferType() {
        return new RequestOfferType();
    }

    /**
     * Create an instance of {@link SubStoragesType }
     * 
     */
    public SubStoragesType createSubStoragesType() {
        return new SubStoragesType();
    }

    /**
     * Create an instance of {@link ItemContractType }
     * 
     */
    public ItemContractType createItemContractType() {
        return new ItemContractType();
    }

    /**
     * Create an instance of {@link ListUserCodeType }
     * 
     */
    public ListUserCodeType createListUserCodeType() {
        return new ListUserCodeType();
    }

    /**
     * Create an instance of {@link RequestParameterType }
     * 
     */
    public RequestParameterType createRequestParameterType() {
        return new RequestParameterType();
    }

    /**
     * Create an instance of {@link ListVydejkaType }
     * 
     */
    public ListVydejkaType createListVydejkaType() {
        return new ListVydejkaType();
    }

    /**
     * Create an instance of {@link ItemNameType }
     * 
     */
    public ItemNameType createItemNameType() {
        return new ItemNameType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAccount")
    public JAXBElement<ListAccountType> createListAccount(ListAccountType value) {
        return new JAXBElement<ListAccountType>(_ListAccount_QNAME, ListAccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountingDoubleEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "createAccountingDoubleEntry")
    public JAXBElement<CreateAccountingDoubleEntryType> createCreateAccountingDoubleEntry(CreateAccountingDoubleEntryType value) {
        return new JAXBElement<CreateAccountingDoubleEntryType>(_CreateAccountingDoubleEntry_QNAME, CreateAccountingDoubleEntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfferRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listOfferRequest")
    public JAXBElement<ListOfferRequestType> createListOfferRequest(ListOfferRequestType value) {
        return new JAXBElement<ListOfferRequestType>(_ListOfferRequest_QNAME, ListOfferRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListCategoryRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listCategoryRequest")
    public JAXBElement<ListCategoryRequestType> createListCategoryRequest(ListCategoryRequestType value) {
        return new JAXBElement<ListCategoryRequestType>(_ListCategoryRequest_QNAME, ListCategoryRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListStorageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listStorage")
    public JAXBElement<ListStorageType> createListStorage(ListStorageType value) {
        return new JAXBElement<ListStorageType>(_ListStorage_QNAME, ListStorageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListUserCodePackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listUserCodePack")
    public JAXBElement<ListUserCodePackType> createListUserCodePack(ListUserCodePackType value) {
        return new JAXBElement<ListUserCodePackType>(_ListUserCodePack_QNAME, ListUserCodePackType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListCategoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listCategory")
    public JAXBElement<ListCategoryType> createListCategory(ListCategoryType value) {
        return new JAXBElement<ListCategoryType>(_ListCategory_QNAME, ListCategoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListEnquiryRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listEnquiryRequest")
    public JAXBElement<ListEnquiryRequestType> createListEnquiryRequest(ListEnquiryRequestType value) {
        return new JAXBElement<ListEnquiryRequestType>(_ListEnquiryRequest_QNAME, ListEnquiryRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListIntParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listIntParam")
    public JAXBElement<ListIntParamType> createListIntParam(ListIntParamType value) {
        return new JAXBElement<ListIntParamType>(_ListIntParam_QNAME, ListIntParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListPrijemkaRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listPrijemkaRequest")
    public JAXBElement<ListPrijemkaRequestType> createListPrijemkaRequest(ListPrijemkaRequestType value) {
        return new JAXBElement<ListPrijemkaRequestType>(_ListPrijemkaRequest_QNAME, ListPrijemkaRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listCashRequest")
    public JAXBElement<ListRequestType> createListCashRequest(ListRequestType value) {
        return new JAXBElement<ListRequestType>(_ListCashRequest_QNAME, ListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListStockType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listStock")
    public JAXBElement<ListStockType> createListStock(ListStockType value) {
        return new JAXBElement<ListStockType>(_ListStock_QNAME, ListStockType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListContractType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listContract")
    public JAXBElement<ListContractType> createListContract(ListContractType value) {
        return new JAXBElement<ListContractType>(_ListContract_QNAME, ListContractType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListBalanceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listBalanceRequest")
    public JAXBElement<ListBalanceRequestType> createListBalanceRequest(ListBalanceRequestType value) {
        return new JAXBElement<ListBalanceRequestType>(_ListBalanceRequest_QNAME, ListBalanceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListActivityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listActivity")
    public JAXBElement<ListActivityType> createListActivity(ListActivityType value) {
        return new JAXBElement<ListActivityType>(_ListActivity_QNAME, ListActivityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAddressBookRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAddressBookRequest")
    public JAXBElement<ListAddressBookRequestType> createListAddressBookRequest(ListAddressBookRequestType value) {
        return new JAXBElement<ListAddressBookRequestType>(_ListAddressBookRequest_QNAME, ListAddressBookRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListBalanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listBalance")
    public JAXBElement<ListBalanceType> createListBalance(ListBalanceType value) {
        return new JAXBElement<ListBalanceType>(_ListBalance_QNAME, ListBalanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInvoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listInvoice")
    public JAXBElement<ListInvoiceType> createListInvoice(ListInvoiceType value) {
        return new JAXBElement<ListInvoiceType>(_ListInvoice_QNAME, ListInvoiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listSellingPriceRequest")
    public JAXBElement<ListRequestType> createListSellingPriceRequest(ListRequestType value) {
        return new JAXBElement<ListRequestType>(_ListSellingPriceRequest_QNAME, ListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListPrijemkaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listPrijemka")
    public JAXBElement<ListPrijemkaType> createListPrijemka(ListPrijemkaType value) {
        return new JAXBElement<ListPrijemkaType>(_ListPrijemka_QNAME, ListPrijemkaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfferType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listOffer")
    public JAXBElement<ListOfferType> createListOffer(ListOfferType value) {
        return new JAXBElement<ListOfferType>(_ListOffer_QNAME, ListOfferType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listCentreRequest")
    public JAXBElement<ListRequestType> createListCentreRequest(ListRequestType value) {
        return new JAXBElement<ListRequestType>(_ListCentreRequest_QNAME, ListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAddressBookType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAddressBook")
    public JAXBElement<ListAddressBookType> createListAddressBook(ListAddressBookType value) {
        return new JAXBElement<ListAddressBookType>(_ListAddressBook_QNAME, ListAddressBookType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestAgendasType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listNumericSeriesRequest")
    public JAXBElement<ListRequestAgendasType> createListNumericSeriesRequest(ListRequestAgendasType value) {
        return new JAXBElement<ListRequestAgendasType>(_ListNumericSeriesRequest_QNAME, ListRequestAgendasType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListParameterRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listParameterRequest")
    public JAXBElement<ListParameterRequestType> createListParameterRequest(ListParameterRequestType value) {
        return new JAXBElement<ListParameterRequestType>(_ListParameterRequest_QNAME, ListParameterRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestStoresType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listStorageRequest")
    public JAXBElement<ListRequestStoresType> createListStorageRequest(ListRequestStoresType value) {
        return new JAXBElement<ListRequestStoresType>(_ListStorageRequest_QNAME, ListRequestStoresType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestAgendasType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAccountingSingleEntryRequest")
    public JAXBElement<ListRequestAgendasType> createListAccountingSingleEntryRequest(ListRequestAgendasType value) {
        return new JAXBElement<ListRequestAgendasType>(_ListAccountingSingleEntryRequest_QNAME, ListRequestAgendasType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListVydejkaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listVydejka")
    public JAXBElement<ListVydejkaType> createListVydejka(ListVydejkaType value) {
        return new JAXBElement<ListVydejkaType>(_ListVydejka_QNAME, ListVydejkaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestAgendasType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAccountingDoubleEntryRequest")
    public JAXBElement<ListRequestAgendasType> createListAccountingDoubleEntryRequest(ListRequestAgendasType value) {
        return new JAXBElement<ListRequestAgendasType>(_ListAccountingDoubleEntryRequest_QNAME, ListRequestAgendasType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listContractRequest")
    public JAXBElement<ListRequestType> createListContractRequest(ListRequestType value) {
        return new JAXBElement<ListRequestType>(_ListContractRequest_QNAME, ListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listParameter")
    public JAXBElement<ListParameterType> createListParameter(ListParameterType value) {
        return new JAXBElement<ListParameterType>(_ListParameter_QNAME, ListParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOrderRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listOrderRequest")
    public JAXBElement<ListOrderRequestType> createListOrderRequest(ListOrderRequestType value) {
        return new JAXBElement<ListOrderRequestType>(_ListOrderRequest_QNAME, ListOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listActivityRequest")
    public JAXBElement<ListRequestType> createListActivityRequest(ListRequestType value) {
        return new JAXBElement<ListRequestType>(_ListActivityRequest_QNAME, ListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAccountRequest")
    public JAXBElement<ListRequestType> createListAccountRequest(ListRequestType value) {
        return new JAXBElement<ListRequestType>(_ListAccountRequest_QNAME, ListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOrderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listOrder")
    public JAXBElement<ListOrderType> createListOrder(ListOrderType value) {
        return new JAXBElement<ListOrderType>(_ListOrder_QNAME, ListOrderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInvoiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listInvoiceRequest")
    public JAXBElement<ListInvoiceRequestType> createListInvoiceRequest(ListInvoiceRequestType value) {
        return new JAXBElement<ListInvoiceRequestType>(_ListInvoiceRequest_QNAME, ListInvoiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountingSingleEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAccountingSingleEntry")
    public JAXBElement<ListAccountingSingleEntryType> createListAccountingSingleEntry(ListAccountingSingleEntryType value) {
        return new JAXBElement<ListAccountingSingleEntryType>(_ListAccountingSingleEntry_QNAME, ListAccountingSingleEntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountingDoubleEntryResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "createAccountingDoubleEntryResponse")
    public JAXBElement<CreateAccountingDoubleEntryResponseType> createCreateAccountingDoubleEntryResponse(CreateAccountingDoubleEntryResponseType value) {
        return new JAXBElement<CreateAccountingDoubleEntryResponseType>(_CreateAccountingDoubleEntryResponse_QNAME, CreateAccountingDoubleEntryResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListUserCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listUserCode")
    public JAXBElement<ListUserCodeType> createListUserCode(ListUserCodeType value) {
        return new JAXBElement<ListUserCodeType>(_ListUserCode_QNAME, ListUserCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListIntParamRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listIntParamRequest")
    public JAXBElement<ListIntParamRequestType> createListIntParamRequest(ListIntParamRequestType value) {
        return new JAXBElement<ListIntParamRequestType>(_ListIntParamRequest_QNAME, ListIntParamRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListNumericSeriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listNumericSeries")
    public JAXBElement<ListNumericSeriesType> createListNumericSeries(ListNumericSeriesType value) {
        return new JAXBElement<ListNumericSeriesType>(_ListNumericSeries_QNAME, ListNumericSeriesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListUserCodeRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listUserCodeRequest")
    public JAXBElement<ListUserCodeRequestType> createListUserCodeRequest(ListUserCodeRequestType value) {
        return new JAXBElement<ListUserCodeRequestType>(_ListUserCodeRequest_QNAME, ListUserCodeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListCentreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listCentre")
    public JAXBElement<ListCentreType> createListCentre(ListCentreType value) {
        return new JAXBElement<ListCentreType>(_ListCentre_QNAME, ListCentreType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListCashType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listCash")
    public JAXBElement<ListCashType> createListCash(ListCashType value) {
        return new JAXBElement<ListCashType>(_ListCash_QNAME, ListCashType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListEnquiryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listEnquiry")
    public JAXBElement<ListEnquiryType> createListEnquiry(ListEnquiryType value) {
        return new JAXBElement<ListEnquiryType>(_ListEnquiry_QNAME, ListEnquiryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountingDoubleEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAccountingDoubleEntry")
    public JAXBElement<ListAccountingDoubleEntryType> createListAccountingDoubleEntry(ListAccountingDoubleEntryType value) {
        return new JAXBElement<ListAccountingDoubleEntryType>(_ListAccountingDoubleEntry_QNAME, ListAccountingDoubleEntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListSellingPriceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listSellingPrice")
    public JAXBElement<ListSellingPriceType> createListSellingPrice(ListSellingPriceType value) {
        return new JAXBElement<ListSellingPriceType>(_ListSellingPrice_QNAME, ListSellingPriceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListVydejkaRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listVydejkaRequest")
    public JAXBElement<ListVydejkaRequestType> createListVydejkaRequest(ListVydejkaRequestType value) {
        return new JAXBElement<ListVydejkaRequestType>(_ListVydejkaRequest_QNAME, ListVydejkaRequestType.class, null, value);
    }

}
