//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.14 at 09:43:22 PM CET 
//


package cz.stormware.schema.list;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.list package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListInvoice_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listInvoice");
    private final static QName _ListAddressBook_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAddressBook");
    private final static QName _ListInvoiceRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listInvoiceRequest");
    private final static QName _ListAddressBookRequest_QNAME = new QName("http://www.stormware.cz/schema/list.xsd", "listAddressBookRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.list
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListRequestType }
     * 
     */
    public ListRequestType createListRequestType() {
        return new ListRequestType();
    }

    /**
     * Create an instance of {@link ListInvoiceType }
     * 
     */
    public ListInvoiceType createListInvoiceType() {
        return new ListInvoiceType();
    }

    /**
     * Create an instance of {@link ListInvoiceRequestType }
     * 
     */
    public ListInvoiceRequestType createListInvoiceRequestType() {
        return new ListInvoiceRequestType();
    }

    /**
     * Create an instance of {@link ListAddressBookType }
     * 
     */
    public ListAddressBookType createListAddressBookType() {
        return new ListAddressBookType();
    }

    /**
     * Create an instance of {@link RequestAddressBookType }
     * 
     */
    public RequestAddressBookType createRequestAddressBookType() {
        return new RequestAddressBookType();
    }

    /**
     * Create an instance of {@link SelectedIcoType }
     * 
     */
    public SelectedIcoType createSelectedIcoType() {
        return new SelectedIcoType();
    }

    /**
     * Create an instance of {@link ListAddressBookRequestType }
     * 
     */
    public ListAddressBookRequestType createListAddressBookRequestType() {
        return new ListAddressBookRequestType();
    }

    /**
     * Create an instance of {@link FilterFieldsType }
     * 
     */
    public FilterFieldsType createFilterFieldsType() {
        return new FilterFieldsType();
    }

    /**
     * Create an instance of {@link SelectedNumbersType }
     * 
     */
    public SelectedNumbersType createSelectedNumbersType() {
        return new SelectedNumbersType();
    }

    /**
     * Create an instance of {@link RequestInvoiceType }
     * 
     */
    public RequestInvoiceType createRequestInvoiceType() {
        return new RequestInvoiceType();
    }

    /**
     * Create an instance of {@link ItemNumericSeriesType }
     * 
     */
    public ItemNumericSeriesType createItemNumericSeriesType() {
        return new ItemNumericSeriesType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ItemNameType }
     * 
     */
    public ItemNameType createItemNameType() {
        return new ItemNameType();
    }

    /**
     * Create an instance of {@link SelectedCompanysType }
     * 
     */
    public SelectedCompanysType createSelectedCompanysType() {
        return new SelectedCompanysType();
    }

    /**
     * Create an instance of {@link ListVersionType }
     * 
     */
    public ListVersionType createListVersionType() {
        return new ListVersionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInvoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listInvoice")
    public JAXBElement<ListInvoiceType> createListInvoice(ListInvoiceType value) {
        return new JAXBElement<ListInvoiceType>(_ListInvoice_QNAME, ListInvoiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAddressBookType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAddressBook")
    public JAXBElement<ListAddressBookType> createListAddressBook(ListAddressBookType value) {
        return new JAXBElement<ListAddressBookType>(_ListAddressBook_QNAME, ListAddressBookType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInvoiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listInvoiceRequest")
    public JAXBElement<ListInvoiceRequestType> createListInvoiceRequest(ListInvoiceRequestType value) {
        return new JAXBElement<ListInvoiceRequestType>(_ListInvoiceRequest_QNAME, ListInvoiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAddressBookRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/list.xsd", name = "listAddressBookRequest")
    public JAXBElement<ListAddressBookRequestType> createListAddressBookRequest(ListAddressBookRequestType value) {
        return new JAXBElement<ListAddressBookRequestType>(_ListAddressBookRequest_QNAME, ListAddressBookRequestType.class, null, value);
    }

}
