//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.list;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import cz.stormware.schema.type.ParameterAgendaType;


/**
 * <p>Java class for requestParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="idsAgenda" use="required" type="{http://www.stormware.cz/schema/type.xsd}parameterAgendaType" />
 *       &lt;attribute name="idsUserAgenda" type="{http://www.stormware.cz/schema/type.xsd}string10" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestParameterType")
public class RequestParameterType {

    @XmlAttribute(required = true)
    protected ParameterAgendaType idsAgenda;
    @XmlAttribute
    protected String idsUserAgenda;

    /**
     * Gets the value of the idsAgenda property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterAgendaType }
     *     
     */
    public ParameterAgendaType getIdsAgenda() {
        return idsAgenda;
    }

    /**
     * Sets the value of the idsAgenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterAgendaType }
     *     
     */
    public void setIdsAgenda(ParameterAgendaType value) {
        this.idsAgenda = value;
    }

    /**
     * Gets the value of the idsUserAgenda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdsUserAgenda() {
        return idsUserAgenda;
    }

    /**
     * Sets the value of the idsUserAgenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdsUserAgenda(String value) {
        this.idsUserAgenda = value;
    }

}
