//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.list;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import cz.stormware.schema.type.Boolean;


/**
 * <p>Java class for requestBalanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestBalanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="adjustTo" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="groupByDoc" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="removeBalancedRec" type="{http://www.stormware.cz/schema/type.xsd}boolean" minOccurs="0"/>
 *         &lt;element name="pairing" type="{http://www.stormware.cz/schema/list.xsd}listBalancePairingType"/>
 *         &lt;element name="userFilterName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestBalanceType", propOrder = {
    "dateTo",
    "adjustTo",
    "groupByDoc",
    "removeBalancedRec",
    "pairing",
    "userFilterName"
})
public class RequestBalanceType {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateTo;
    @XmlElement(defaultValue = "0.01")
    protected Double adjustTo;
    @XmlElement(defaultValue = "true")
    protected Boolean groupByDoc;
    @XmlElement(defaultValue = "true")
    protected Boolean removeBalancedRec;
    @XmlElement(required = true)
    protected ListBalancePairingType pairing;
    protected String userFilterName;

    /**
     * Gets the value of the dateTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTo() {
        return dateTo;
    }

    /**
     * Sets the value of the dateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTo(XMLGregorianCalendar value) {
        this.dateTo = value;
    }

    /**
     * Gets the value of the adjustTo property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdjustTo() {
        return adjustTo;
    }

    /**
     * Sets the value of the adjustTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdjustTo(Double value) {
        this.adjustTo = value;
    }

    /**
     * Gets the value of the groupByDoc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getGroupByDoc() {
        return groupByDoc;
    }

    /**
     * Sets the value of the groupByDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGroupByDoc(Boolean value) {
        this.groupByDoc = value;
    }

    /**
     * Gets the value of the removeBalancedRec property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getRemoveBalancedRec() {
        return removeBalancedRec;
    }

    /**
     * Sets the value of the removeBalancedRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoveBalancedRec(Boolean value) {
        this.removeBalancedRec = value;
    }

    /**
     * Gets the value of the pairing property.
     * 
     * @return
     *     possible object is
     *     {@link ListBalancePairingType }
     *     
     */
    public ListBalancePairingType getPairing() {
        return pairing;
    }

    /**
     * Sets the value of the pairing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListBalancePairingType }
     *     
     */
    public void setPairing(ListBalancePairingType value) {
        this.pairing = value;
    }

    /**
     * Gets the value of the userFilterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFilterName() {
        return userFilterName;
    }

    /**
     * Sets the value of the userFilterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFilterName(String value) {
        this.userFilterName = value;
    }

}
