//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.isdoc.namespace.invoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Identifikace zápisu v rejst\u0159íku
 * 
 * <p>Java class for RegisterIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegisterIdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegisterKeptAt" type="{http://isdoc.cz/namespace/invoice}RegisterKeptAtType"/>
 *         &lt;element name="RegisterFileRef" type="{http://isdoc.cz/namespace/invoice}RegisterFileRefType"/>
 *         &lt;element name="RegisterDate" type="{http://isdoc.cz/namespace/invoice}RegisterDateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterIdentificationType", propOrder = {
    "registerKeptAt",
    "registerFileRef",
    "registerDate"
})
public class RegisterIdentificationType {

    @XmlElement(name = "RegisterKeptAt", required = true)
    protected String registerKeptAt;
    @XmlElement(name = "RegisterFileRef", required = true)
    protected String registerFileRef;
    @XmlElement(name = "RegisterDate", required = true)
    protected XMLGregorianCalendar registerDate;

    /**
     * Gets the value of the registerKeptAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterKeptAt() {
        return registerKeptAt;
    }

    /**
     * Sets the value of the registerKeptAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterKeptAt(String value) {
        this.registerKeptAt = value;
    }

    /**
     * Gets the value of the registerFileRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterFileRef() {
        return registerFileRef;
    }

    /**
     * Sets the value of the registerFileRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterFileRef(String value) {
        this.registerFileRef = value;
    }

    /**
     * Gets the value of the registerDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegisterDate() {
        return registerDate;
    }

    /**
     * Sets the value of the registerDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegisterDate(XMLGregorianCalendar value) {
        this.registerDate = value;
    }

}
