//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.isdoc.namespace.invoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Šarže/sériové \u010díslo
 * 
 * <p>Java class for StoreBatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoreBatchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://isdoc.cz/namespace/invoice}NameType"/>
 *         &lt;element name="Note" type="{http://isdoc.cz/namespace/invoice}NoteType" minOccurs="0"/>
 *         &lt;element name="ExpirationDate" type="{http://isdoc.cz/namespace/invoice}ExpirationDateType" minOccurs="0"/>
 *         &lt;element name="Specification" type="{http://isdoc.cz/namespace/invoice}SpecificationType" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://isdoc.cz/namespace/invoice}QuantityType"/>
 *         &lt;element name="BatchOrSerialNumber" type="{http://isdoc.cz/namespace/invoice}BatchOrSerialNumberType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoreBatchType", propOrder = {
    "name",
    "note",
    "expirationDate",
    "specification",
    "quantity",
    "batchOrSerialNumber"
})
public class StoreBatchType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Note")
    protected NoteType note;
    @XmlElement(name = "ExpirationDate")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(name = "Specification")
    protected String specification;
    @XmlElement(name = "Quantity", required = true)
    protected QuantityType quantity;
    @XmlElement(name = "BatchOrSerialNumber", required = true)
    protected BatchOrSerialNumberType batchOrSerialNumber;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link NoteType }
     *     
     */
    public NoteType getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteType }
     *     
     */
    public void setNote(NoteType value) {
        this.note = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecification(String value) {
        this.specification = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setQuantity(QuantityType value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the batchOrSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BatchOrSerialNumberType }
     *     
     */
    public BatchOrSerialNumberType getBatchOrSerialNumber() {
        return batchOrSerialNumber;
    }

    /**
     * Sets the value of the batchOrSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchOrSerialNumberType }
     *     
     */
    public void setBatchOrSerialNumber(BatchOrSerialNumberType value) {
        this.batchOrSerialNumber = value;
    }

}
