//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.13 at 11:47:26 PM CET 
//


package cz.stormware.schema.codelist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for codeListPackType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="codeListPackType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="codeListPackItem" type="{http://www.stormware.cz/schema/codelist.xsd}codeListPackItemType"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "codeListPackType", propOrder = {
    "codeListPackItem"
})
public class CodeListPackType {

    protected CodeListPackItemType codeListPackItem;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the codeListPackItem property.
     * 
     * @return
     *     possible object is
     *     {@link CodeListPackItemType }
     *     
     */
    public CodeListPackItemType getCodeListPackItem() {
        return codeListPackItem;
    }

    /**
     * Sets the value of the codeListPackItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeListPackItemType }
     *     
     */
    public void setCodeListPackItem(CodeListPackItemType value) {
        this.codeListPackItem = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
